USE [master]
GO

/****** Object:  Database [BoVoyage]    Script Date: 14/06/2018 09:47:35 ******/
CREATE DATABASE [BoVoyage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bo_Voyage', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Bo_Voyage.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Bo_Voyage_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Bo_Voyage_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [BoVoyage] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BoVoyage].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BoVoyage] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BoVoyage] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BoVoyage] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BoVoyage] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BoVoyage] SET ARITHABORT OFF 
GO

ALTER DATABASE [BoVoyage] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BoVoyage] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BoVoyage] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BoVoyage] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BoVoyage] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BoVoyage] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BoVoyage] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BoVoyage] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BoVoyage] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BoVoyage] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BoVoyage] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BoVoyage] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BoVoyage] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BoVoyage] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BoVoyage] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BoVoyage] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BoVoyage] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BoVoyage] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BoVoyage] SET  MULTI_USER 
GO

ALTER DATABASE [BoVoyage] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BoVoyage] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BoVoyage] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BoVoyage] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BoVoyage] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BoVoyage] SET QUERY_STORE = OFF
GO

USE [BoVoyage]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [BoVoyage] SET  READ_WRITE 
GO

